- name: Include variables
  ansible.builtin.include_vars:
    dir: "{{ project_path }}/ansible/group_vars"
      
- name: Add secrets for 1Password integration
  kubernetes.core.k8s:
    state: present
    definition: 
      apiVersion: v1
      kind: Secret
      type: Opaque             
      metadata:
        name: "onepassword-token"
        namespace: "kube-system"     
      data:
        token: "{{ onepass_token }}"

- name: Add secrets for 1Password integration
  kubernetes.core.k8s:
    state: present
    definition: 
      apiVersion: v1
      kind: Secret
      type: Opaque             
      metadata:
        name: "op-credentials"
        namespace: "kube-system"     
      data:
        1password-credentials.json: "{{ onepass_credentials }}"