---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: flux-system
spec:
  interval: 10m
  url: oci://charts.bitnami.com/bitnami
  type: OCI
  timeout: 3m