- name: Stop VM with force
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    api_host: "{{ proxmox_host }}"
    node: "{{ item.node }}"
    vmid: "{{ item.vmid }}"
    state: stopped
    force: true
    timeout: 30
  loop: "{{ vm_list }}"
  ignore_errors: true

- name: Remove VM
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    api_host: "{{ proxmox_host }}"
    vmid: "{{ item.vmid }}"
    state: absent
  loop: "{{ vm_list }}"
  ignore_errors: true

- name: Remove known_hosts
  delegate_to: localhost
  ansible.builtin.known_hosts:
    name: "{{ item.name }}.{{ domain_name }}"
    state: absent
  loop: "{{ vm_list }}"
  ignore_errors: true
