apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: my-http-route
  namespace: cilium
spec:
  parentRefs:
    - name: cilium-gw
      port: 443
      namespace: cilium
  hostnames:
    - "gateway.cooney.site"
  rules:
  - backendRefs:
    - name: hubble-ui
      port: 80
    # - matches:
    #     - path:
    #         type: PathPrefix
    #         value: /hubble
      # filters:
      #   - type: URLRewrite
      #     urlRewrite:
      #       path:
      #         type: ReplacePrefixMatch
      #         replacePrefixMatch: /
