apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ingres-controller-pool"
  labels:
    pool: "ingres-controller-pool"
spec:
  blocks:
  - cidr: "172.16.1.190/32"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
  labels:
    pool: "lb-pool"
spec:
  blocks:
  - start: "172.16.1.191"
    stop: "172.16.1.199"  
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: "hubble-ui-pool"
  labels:
    pool: "hubble-ui-pool"
spec:
  blocks:
  - cidr: "172.16.1.180/32"