apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 172.16.1.180
  labels:
    app.kubernetes.io/name: hubble-ui
    app.kubernetes.io/part-of: cilium
    k8s-app: hubble-ui
    # pool: "{{ ippool.hubble_ui.name }}"
    serviceType: core 
  name: hubble-ui-cilium
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: io.cilium/l2-announcer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    k8s-app: hubble-ui
  type: LoadBalancer
  externalTrafficPolicy: Cluster
