# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:BLjWL59rnqC50Lv10xDr/VdC7lXMAXfVS5sV3AX7oP3ILVWwdQFbawg1dVQE0s/KhR9pzStLcfxQLdoJt3w1J3K+4JpBprP4iCkobn8i6fn7sjqapVh+gVfefJZMW+WUerai/7FLQ1GDcQ+eVLiA67RwegyGkffrWwnMvC96RN+q+VvjRdM+dNWzFRXzrveQuT2TzRTDtK/JQbqjcxbOjtCQa7JAQcnAlzYMkzqadjF1pgH11g==,iv:cia0fxKJgcQ+g8XRPBJ8mqxwElS9pjr44yofFL2NwCo=,tag:SSFG6O0piCdjwXlV8KPfCw==,type:str]
sops:
  age:
    - recipient: age1sp4tkummlyx7cd6zeny0532kkkvvs3vvl9ut0dvjshsnykktja3qcaekmn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBob3RiUGxvTjFrQzA5Nzli
        QWhFWnVzODNka1YwSmtMY3k1TzRPUGpWRFVFCkxEdGNKVzNUNU1rZmxvTktuZWRC
        cDRiOHhBQkU1dGRzamczSDRzQTFyUTAKLS0tIGlFSWl6THpqM3FkdTJVMUJycEty
        NUdQSnZLMkNvM1pLbTIzRit0K1IwdjQKbmmQE8UjQWF4oVyJYhRMCL7Zvcmt6qAb
        goBER1RvqBHlI7wUOR70OGoEQn+zv6rKltJawsc784/ikMX6lmtkdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-09T01:04:24Z"
  mac: ENC[AES256_GCM,data:TQqH7GJRRh/3/BtLR9pBgYkgbpv3/aALTdwUD5s2MGO6+NsYsch/P1SBCMJoIhO7p5Me5BTUkB94A0MaSaBxAs/Zy0a3Jd1OTyffStV6Zf8PWIKWLJi77dXxJZujMxXGruSgs8SK6+gH5w/fhaA/nqpc14HnEm+Nm1OuQHGSa9M=,iv:g+vNGd3OqU3JsMQQtaM4HxS8+6NE3BtxYO/0Iuaw7hg=,tag:EapR9DQnpuxm3eFvvvdqRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
