---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1sp4tkummlyx7cd6zeny0532kkkvvs3vvl9ut0dvjshsnykktja3qcaekmn"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1sp4tkummlyx7cd6zeny0532kkkvvs3vvl9ut0dvjshsnykktja3qcaekmn"
stores:
  yaml:
    indent: 2
