---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sonarr
              tag: 4.0.13.2932
              pullPolicy: IfNotPresent
            env:
              TZ: America/New_York

            probes:
              liveness:
                enabled: true
                ## Set this to true if you wish to specify your own livenessProbe
                custom: true
                ## The spec field contains the values for the default livenessProbe.
                ## If you selected custom: true, this field holds the definition of the livenessProbe.
                spec:
                  exec:
                    command:
                    - /usr/bin/env
                    - bash
                    - -c
                    - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while
                      read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
                  failureThreshold: 5
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10

            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              fsGroupChangePolicy: "OnRootMismatch"
            resources:
              requests:
                memory: 350Mi
                cpu: 25m
              limits:
                memory: 500Mi
    service:
      main:
        type: NodePort
        ports:
          - name: http
            port: 8989
            targetPort: 8989
            nodePort: 30036
            protocol: TCP
          # http:
          #   port: 8989
    persistence:
      config:
        enabled: true
        storageClass: sonarr-config
        existingClaim: nfs-sonarr-config-pvc
        globalMounts:
          - path: /config
      media:
        enabled: true
        # storageClass: media-tvshows
        existingClaim: nfs-media-tvshows-pvc
        globalMounts:
         - path: /media/tvshows
    # ingress:
    #   main:
    #     enabled: true
    #     ingressClassName: nginx-tailscale
    #     hosts:
    #       - host: &host tv.cooney.site
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #     tls:
    #       - hosts:
    #         - *host