# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:tGO6nysVbh15RzCrKk+cQ8cJNBKu4Zf/n0bq+inXlSKQHBC+Ig3vtw==,iv:9H7DFui7JMP63E9Y9mlkaF4wc6WyU3+5BoZRN+7QRwY=,tag:12/AW+0tQGXa0XvNWB/w+w==,type:str]
sops:
  age:
    - recipient: age15dkhphjdz036mmn5l0s2623kpdz3d54jcyh9nv63l4w2fjkkzy0qddz7cz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT0hzejFwaGRJRE95enk2
        RFlocUZBeGovclp2WlJQZHJnVmhGa1pZZFFZCmNZaTVDNlNTQTh6TitTUzhYSmF3
        T1Qya2wrZ1N0eXF4TmdDcXFTOHNhMEUKLS0tIHVOU1ZvRnE4clIvaFpqdXo4NkpV
        K2ZmS3V3clpIaTV5REFjUWR2MHBpNXcKQ392sFSQgkY6IdsZtxHEz4fNUXQvQc5c
        /Ro2nJjWRQHaDK5OLGTbYopgTn91H+D53UJSZd1jXpYM7G3Ucs3GYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-11T21:04:37Z"
  mac: ENC[AES256_GCM,data:7jjcwVHrFApvyxP5qVt4kA6iJ22iMmhhGPRA5YCggWnRuA7Npd23FAC/fbr6wnHCMfBTcPLtADnCl6w5/O9n2dbAKEUyFcNDccYh5JnxPDy3fOV7mrKZqNepIlCjOva5ixsq2dah9Ap2vygi3fs+/qJyUbyE3LIuS9z+mGO4XzA=,iv:IdxcP/L/O+6uRP/m1zSVNNrLZ1fk5Sy9NuqQ1HNBeQo=,tag:yxJRRkhHZYf9enmsBXkxiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
