---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password-charts
  namespace: kube-system
spec:
  interval: 30m
  url: https://1password.github.io/connect-helm-charts/