---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 10m
  url: https://charts.external-secrets.io
  timeout: 3m
