---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: &app external-secrets
  namespace: &ns kube-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  wait: true
  prune: true
  path: "./kubernetes/kube-system/external-secrets/external-secrets"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: *app
      namespace: *ns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: &app onepassword
  namespace: &ns kube-system
spec:
  dependsOn:
    - name: external-secrets
  path: "./kubernetes/kube-system/external-secrets/1password"
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: *app
      namespace: *ns
