---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-secrets
    template:
      data:
        CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
        CLOUDFLARE_EMAIL: "{{ .CLOUDFLARE_EMAIL }}"
        CLOUDFLARE_DOMAIN: "{{ .CLOUDFLARE_DOMAIN }}"
  dataFrom:
    - extract:
        key: cloudflare
