apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: nginx-ingress-controller
      version: 9.x
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 2h
  values:
    controller:
      service:
        type: "NodePort"
    admissionWebhooks:
      enabled: false