api_host: '{{inventory_hostname}}'
drive_storage: local-zfs
drive_format: qcow2
snippets_storage: local
snippets_path: '/var/lib/vz/snippets/'
image_storage: local
linux_bridge: vmbr0
ciuser: "{{ lookup('community.general.onepassword', 'ciuser', vault='kubernetes', field='username') }}"
ciuser_sshkey: "{{ lookup('community.general.onepassword', 'ciuser', vault='kubernetes', field='sshkey') }}"
proxmox_host: "{{ groups['pvenodes'][0] }}"
proxmox_user: "{{ lookup('community.general.onepassword', 'proxmox_user', vault='kubernetes', field='username') }}"
proxmox_token_id: "{{ lookup('community.general.onepassword', 'proxmox_user', vault='kubernetes', field='token_id') }}"
proxmox_token_secret: "{{ lookup('community.general.onepassword', 'proxmox_user', vault='kubernetes', field='token_id_secret') }}"
os_images:
  - name: ubuntu_24.04
    cloud_init_file: 'noble-server-cloudimg-amd64.qcow2'
    image_url: 'https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img'
    image_checksum: 'sha256:85af38f453feaa3d6fbc6aba3b2a843b5b10e8ce273a24047259bb7fa47ff4c5'
    state: present
k3snodes:
  - name: kube01
    vmid: 601
    node: pve01
    image_file: noble-server-cloudimg-amd64.qcow2
    cores: 1
    memory: 2048
    ipv4mode: static
    ipv4_address: 172.16.1.171/24
    ipv4_gateway: 172.16.1.1
    mac_address: bc:24:11:3e:bf:63
    state: new
  - name: kube02
    vmid: 602
    node: pve02
    image_file: noble-server-cloudimg-amd64.qcow2
    cores: 1
    memory: 2048
    ipv4mode: static
    ipv4_address: 172.16.1.172/24
    ipv4_gateway: 172.16.1.1
    mac_address: bc:24:11:da:63:2f
    state: new
  - name: kube03
    vmid: 603
    node: pve03
    image_file: noble-server-cloudimg-amd64.qcow2
    cores: 1
    memory: 2048
    ipv4mode: static
    ipv4_address: 172.16.1.173/24
    ipv4_gateway: 172.16.1.1
    mac_address: bc:24:11:2b:1a:9a
    state: new
  - name: kube04
    vmid: 604
    node: pve01
    image_file: noble-server-cloudimg-amd64.qcow2
    cores: 2
    memory: 4096
    ipv4mode: static
    ipv4_address: 172.16.1.174/24
    ipv4_gateway: 172.16.1.1
    mac_address: bc:24:11:d3:e5:70
    state: new
  - name: kube05
    vmid: 605
    node: pve03
    image_file: noble-server-cloudimg-amd64.qcow2
    cores: 2
    memory: 4096
    ipv4mode: static
    ipv4_address: 172.16.1.175/24
    ipv4_gateway: 172.16.1.1
    mac_address: bc:24:11:59:93:0b
    state: new
proxmox_packages:
  - python3-proxmoxer
  - python3-requests
talos_storage: pool
talos_image: talos-nocloud-amd64.iso
talosnodes:
  - name: talos01
    vmid: 701
    node: pve01
    image_file: "{{ talos_image }}"
    cores: 2
    memory: 2048
    ipv4mode: static
    ipv4_address: 172.16.1.171/24
    ipv4_gateway: 172.16.1.1
    mac_address: bc:24:11:56:89:8a
    state: new
  - name: talos02
    vmid: 702
    node: pve02
    image_file: "{{ talos_image }}"
    cores: 2
    memory: 2048
    ipv4mode: static
    ipv4_address: 172.16.1.172/24
    ipv4_gateway: 172.16.1.1
    mac_address: bc:24:11:b5:69:e2
    state: new
  - name: talos03
    vmid: 703
    node: pve03
    image_file: "{{ talos_image }}"
    cores: 2
    memory: 2048
    ipv4mode: static
    ipv4_address: 172.16.1.173/24
    ipv4_gateway: 172.16.1.1
    mac_address: bc:24:11:8c:a3:d0
    state: new
