---
autoDirectNodeRoutes: true
bandwidthManager:
  enabled: true
  bbr: true
bpf:
  datapathMode: netkit
  masquerade: true
  preallocateMaps: true
  # tproxy: true
bgpControlPlane:
  enabled: true
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cni:
  exclusive: false
dashboards:
  enabled: true
devices: eth0
# enableIPv4Masquerade: true
enableIPv4BIGTCP: true
endpointRoutes:
  enabled: true
envoy:
  enabled: true
  rollOutPods: true
# externalIPs:
#   enabled: true
gatewayAPI:
  enabled: true
  enableAlpn: true
  xffNumTrustedHops: 1
  # hostNetwork:
  #   enabled: true
hubble:
  enabled: false
  # ui:
  #   enabled: true
  #   rollOutPods: true
  #   replicas: 1
  #   tolerations:
  #   - key: node-role.kubernetes.io/control-plane
  #     operator: Exists
  #     effect: NoSchedule
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule
  # relay:
  #   enabled: true
  #   replicas: 1
  #   rollOutPods: true
  #   tolerations:
  #   - key: node-role.kubernetes.io/control-plane
  #     operator: Exists
  #     effect: NoSchedule
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule
# ingressController:
#   enabled: true
#   default: true
#   service:
#     externalTrafficPolicy: Cluster
#     type: LoadBalancer
#     loadBalancerIP: "{{ ippool.ingress_controller.ip }}"
#   loadbalancerMode: shared
ipam:
  mode: kubernetes
  # operator:
  #   clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
  #   clusterPoolIPv4MaskSize: 24
# ipv4:
#   enabled: true
ipv4NativeRoutingCIDR: 10.244.0.0/16
# ipv6:
#   enabled: true
k8sServiceHost: 172.16.1.171
k8sServicePort: 6443
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: dsr
# loadBalancerIPs:
#   enabled: true
localRedirectPolicy: true
# namespaceOverride: "cilium"
operator:
  dashboards:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 2
  rollOutPods: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
# tls:
#   secretsNamespace:
#     create: false
