apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-config
  namespace: flux-system
data:
  values.yaml: |
    instance:
      sync:
        kind: GitRepository
        url: https://github.com/andycooney/infrastructure.git
        ref: refs/heads/main
        path: "${PATH}"
        provider: github
        pullSecret: "${TOKEN}"
        name: "${USER}"
        interval: 10m