---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-secrets
    template:
      data:
        REPOSITORY: "{{ .REPOSITORY }}"
        BRANCH: "{{ .BRANCH }}"
        PATH: "{{ .PATH }}"
        TOKEN: "{{ .TOKEN }}"
        TOKENNAME: "{{ .TOKENNAME }}"
        USER: "{{ .USER }}"
  dataFrom:
    - extract:
        key: github
