- name: Create K3s VMs
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    api_host: "{{ proxmox_host }}"
    agent: "enabled=1"
    balloon: 0
    boot: order=scsi0
    cicustom: "user={{ snippets_storage }}:snippets/{{ item.vmid }}-user.yaml"
    cpu: "host"
    ide:
      ide2: '{{ drive_storage }}:cloudinit'
    ipconfig:
      ipconfig0: "ip=dhcp"
    memory: "{{ item.memory }}"
    name: "{{ item.name }}"
    nameservers: "{{ nameservers }}"
    net: '{"net0":"virtio={{ item.mac_address }},bridge={{ linux_bridge }},firewall=1"}'
    node: "{{ item.node }}"
    onboot: "no"
    ostype: "l26"
    scsi:
      scsi0: '{{ drive_storage }}:0,import-from={{ image_storage }}:0/{{ item.image_file }},format={{ drive_format }},iothread=1'
    scsihw: virtio-scsi-single
    serial: '{"serial0":"socket"}'
    sockets: 1
    timeout: 700
    vga: serial0
    vmid: "{{ item.vmid }}"
  loop: "{{ k3snodes }}"
  when:
    - 'item.state == "new"'
  no_log: false

# Update network settings
# A custom file would have been preferred to update the network settings but the problem is it includes a MAC address
# So all VMs will be configured to use DHCP by default, those that need a static IP will be updated
- name: Update network settings
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    api_host: "{{ proxmox_host }}"
    node: "{{ item.node }}"
    vmid: "{{ item.vmid }}"
    ipconfig:
      ipconfig0: "ip={{ item.ipv4_address }},gw={{ item.ipv4_gateway }}"
    timeout: 60
    update: true
  loop: "{{ k3snodes }}"
  when:
    - item.state == "new"
    - item.ipv4mode == 'static'
  no_log: true

 # Resize the disk
 # The Cloud-Init disk is only 2GB
- name: Resize disk
  community.general.proxmox_disk:
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    api_host: "{{ proxmox_host }}"
    vmid: "{{ item.vmid }}"
    disk: "scsi0"
    size: "32G"
    state: "resized"
    timeout: 60
  loop: "{{ k3snodes }}"
  when:
    - 'item.state == "new"'
  no_log: true

# Start VMs
- name: Start VMs
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    api_host: "{{ proxmox_host }}"
    node: "{{ item.node }}"
    vmid: "{{ item.vmid }}"
    state: "started"
  loop: "{{ k3snodes }}"
  when:
    - 'item.state == "new"'
  no_log: true

- name: Pause to wait for hosts to come up
  ansible.builtin.pause:
    seconds: 180
