---
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
  - name: "instance-64514"
    localASN: 64514
    peers:
    - name: "peer-64513-udm"
      localPort: 179
      peerASN: 64513
      peerAddress: 172.16.1.1/32
      peerConfigRef:
        name: "cilium-peer"

---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
    - afi: ipv6
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"

---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "PodCIDR"

# ---
# apiVersion: cilium.io/v2
# kind: CiliumBGPAdvertisement
# metadata:
#   name: pod-ip-pool-advert
#   labels:
#     advertise: bgp
# spec:
#   advertisements:
#     - advertisementType: "CiliumPodIPPool"
#       selector:
#         matchExpressions:
#         - key: thisFakeSelector
#           operator: NotIn
#           values:
#             - 'never-used-value'
