---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 1password-charts
spec:
  interval: 10m
  url: https://raw.githubusercontent.com/1Password/connect-helm-charts/gh-pages/
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: onepassword-values
