---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword
  namespace: flux-system
spec:
  interval: 2m
  chart:
    spec:
      chart: connect
      version: 1.17.x
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
        namespace: flux-system
      interval: 5m
  values:
    namespace: flux-system
    connect:
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
      replicas: 1
    operator:
      create: false
