# Create user cloud-init files
# NOTE: The storage used for these files has to support snippets
- name: Create user cloud-init files
  ansible.builtin.template:
    src: user_template.j2
    dest: '{{ snippets_path }}{{ item.vmid }}-user.yaml'
    owner: root
    group: root
    mode: 0644
  loop: '{{ k3snodes }}'
  no_log: false
