autoDirectNodeRoutes: true
devices: eth0
# enableIPv4Masquerade: true
externalIPs:
  enabled: true
gatewayAPI:
  enabled: true
hubble:
  enabled: true
  ui:
    enabled: true
    rollOutPods: true
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  relay:
    enabled: true
    rollOutPods: true
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
# ingressController:
#   enabled: true
#   default: true
#   service:
#     externalTrafficPolicy: Cluster
#     type: LoadBalancer
#     loadBalancerIP: "{{ ippool.ingress_controller.ip }}"
#   loadbalancerMode: shared
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
    clusterPoolIPv4MaskSize: 24
ipv4:
  enabled: true
ipv4NativeRoutingCIDR: 10.244.0.0/16
ipv6:
  enabled: false
k8sServiceHost: "172.16.1.171"
k8sServicePort: "6443"
kubeProxyReplacement: "true"
l2announcements:
  enabled: true
  # leaseDuration: "{{ cilium.l2.announcements.lease.duration }}"
  # leaseRenewDeadline: "{{ cilium.l2.announcements.lease.renew_deadline }}"
  # leaseRetryPeriod: "{{ cilium.l2.announcements.lease.retry_period }}"
# loadBalancer:
#   l7:
#     backend: envoy
loadBalancerIPs:
  enabled: true
operator:
  replicas: 1
rollOutCiliumPods: true
routingMode: "native"
# set-cilium-node-taints: "false"
tls:
  secretsNamespace:
    create: false
