k3s_version: v1.32.1+k3s1
github_token: "{{ lookup('community.general.onepassword', 'github_user', vault='kubernetes', field='token') }}"
github_user: "{{ lookup('community.general.onepassword', 'github_user', vault='kubernetes', field='username') }}"
github_repo: "{{ lookup('community.general.onepassword', 'github_user', vault='kubernetes', field='repository') }}"
github_branch: "{{ lookup('community.general.onepassword', 'github_user', vault='kubernetes', field='branch') }}"
github_path: "{{ lookup('community.general.onepassword', 'github_user', vault='kubernetes', field='path') }}"
onepass_credentials: "{{ lookup('community.general.onepassword_doc', 'onepass_credentials', vault='kubernetes')  | b64encode }}"
onepass_token: "{{ lookup('community.general.onepassword', 'onepass_token', vault='kubernetes') | b64encode }}"
token: "{{ lookup('community.general.onepassword', 'k3s_token', vault='kubernetes') }}"
k3s_kubectl_binary: "kubectl"
k3s_master_taint: "{{ true if groups['agent'] | default([]) | length >= 1 else false }}"
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
extra_server_args: >-
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}
  --kubelet-arg node-status-update-frequency=5s
  --tls-san {{ api_endpoint }},kube.cooney.site,kube01.cooney.site
  --flannel-backend=none
  --disable-kube-proxy
  --disable-network-policy
  --disable servicelb
  --disable traefik
extra_agent_args:
  --node-taint node.cilium.io/agent-not-ready:NoExecute
  --kubelet-arg node-status-update-frequency=5s
systemd_dir: /etc/systemd/system
k3s_packages:
  - nfs-common
cilium:
  version: 1.17.x
  interface: "eth0"
  l2:
    # blocks:
    # - start: "172.16.1.180"
    #   stop: "172.16.1.199"
    announcements:
      lease:
        duration: 3s
        renew_deadline: 1s
        retry_period: 500ms
  k8s_client_rate_limit:
    qps: 2
    burst: 5
ippool:
  ingress_controller:
    name: "ingres-controller-pool"
    pool:
    - cidr: "172.16.1.190/32"
    ip: "172.16.1.190"
  hubble_ui:
    name: "hubble-ui-pool"
    pool:
    - cidr: "172.16.1.180/32"
    ip: "172.16.1.180"
  lb:
    name: "lb-pool"
    pool:
    - start: "172.16.1.191"
      stop: "172.16.1.199"
