---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: kube-system
spec:
  interval: 5m0s
  wait: true
  timeout: 3m0s
  retryInterval: 2m0s
  path: ./kubernetes/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system