---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${CLOUDFLARE_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            ### api-key requires email; token does not
            email: "${CLOUDFLARE_EMAIL}"
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: CLOUDFLARE_API_TOKEN
        selector:
          dnsZones:
            - "${CLOUDFLARE_DOMAIN}"

  # acme:
  #   server: https://acme-v02.api.letsencrypt.org/directory
  #   email: you@example.com  # your email address for updates
  #   privateKeySecretRef:
  #     name: letsencrypt-dns01-private-key
  #   solvers:
  #   - dns01:
  #       cloudflare:
  #         email: you@example.com # your cloudflare account email address
  #         apiTokenSecretRef:
  #           name: cloudflare-api-key-secret
  #           key: api-key