apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # name of the ExternalSecret & Secret which gets created
  name: cloudflare_api_token
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: cloudflare_token
      property: password
  # - secretKey: secretKey
  #   remoteRef:
  #     # 1password-entry-name
  #     key: "Scaleway Credentials"
  #     # 1password-field
  #     property: secretKey
