- name: Download images and create cloud-init files
  hosts: pvenodes
  become: true
  roles:
    - role: install_packages
      packages: "{{ proxmox_packages }}"
    - download_cloud_init_images
    - create_user_files

- name: Create VMs
  hosts: pvenodes[0]
  become: false
  tasks:
    - name: Create VMs
      include_role:
        name: create_vms

    - name: Wait before cleaning up cloud init files
      delegate_to: localhost
      pause:
        seconds: 15

- name: Celanup cloud-init files
  hosts: pvenodes
  become: true
  tasks:
    - name: Clean up files
      include_role:
        name: delete_k3s_node_cloud_init_files

    - name: Wait for VMs to start
      delegate_to: localhost
      pause:
        seconds: 30