- name: Build k3s VMs
  import_playbook: build_k3s_nodes.yaml

- name: Prepare k3s basic cluster
  import_playbook: prepare_k3s_cluster.yaml

- name: Bootstrap k3s basic cluster
  import_playbook: bootstrap_k3s_cluster.yaml
