- name: Delete Talos VMs
  hosts: pvenodes[0]
  become: false
  gather_facts: false
  vars:
    vm_list: "{{ talosnodes }}"
  tasks:
    - name: Delete VM
      ansible.builtin.include_role:
        name: delete_proxmox_vm
