---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  tasks:
    - name: Install additional packages
      ansible.builtin.include_role:
        name: install_packages
      vars:
        install_packages_list: "{{ k3s_packages }}"

    - name: Process prereq
      ansible.builtin.include_role:
        name: prereq

- name: Setup K3S server
  hosts: server
  become: true
  tasks:
    - name: Install server on first host and init cluster
      ansible.builtin.include_role:
        name: k3s_server
      vars:
        k3s_server_basic_run: true

- name: Setup K3S agent
  hosts: agent
  become: true
  tasks:
    - name: Install k3s agent
      ansible.builtin.include_role:
        name: k3s_agent
