- hosts: pvenodes
  become: true
  tasks:
  roles:
    - delete_k3s_node_cloud_init_files

- hosts: pvenodes[0]
  become: false
  tasks:
  roles:
    - delete_k3s_nodes

- hosts: localhost
  become: false
  gather_facts: false
  roles:
    - delete_known_hosts