- hosts: pvenodes
  become: true
  tasks:
  roles:
    - delete_k3s_node_cloud_init_files

- hosts: pvenodes[0]
  become: false
  tasks:
    - include_role:
        name: delete_k3s_nodes
    
    - name: Install additional packages
      include_role:
        name: delete_known_hosts
