---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
spec:
  interval: 10m
  url: https://charts.external-secrets.io
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  targetNamespace: external-secrets
  interval: 10m
  retryInterval: 3m
  timeout: 3m
  wait: true
  chart:
    spec:
      chart: external-secrets
      version: 0.14.x
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 5m
  values:
    installCRDs: true
    replicaCount: 1
    serviceMonitor:
      enabled: true
    webhook:
      serviceMonitor:
        enabled: true
    # certController:
    #   serviceMonitor:
    #     enabled: true
