apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-tvshows-pv
  namespace: default
spec:
  storageClassName: media-tvshows
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.1.10
    path: "/media/tvshows"
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-tvshows-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data
  resources:
    requests:
      storage: 1Mi