apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sonarr-config-pv
  namespace: default
spec:
  storageClassName: sonarr-config
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.1.10
    path: "/appdata/k8s-sonarr"
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-sonarr-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sonarr-config
  resources:
    requests:
      storage: 1Mi