---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system
  namespace: kubesystem
spec:
  interval: 1m0s
  path: ./kubernetes/kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system