# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://172.16.1.180:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "172.16.1.180"
  - "kube.cooney.site, talos.cooney.site, talos01.cooney.site, talos02.cooney.site, talos03.cooney.site, talos04.cooney.site, talos05.cooney.site"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos01"
    ipAddress: "172.16.1.181"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/d4bf8bf16e1413866902f476a8bdee90264168facc6bbc66e5e8598d4ce2d9cc
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:56:89:8a"
        dhcp: false
        addresses:
          - "172.16.1.181/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.16.1.1"
        mtu: 1500
        vip:
          ip: "172.16.1.180"
  - hostname: "talos02"
    ipAddress: "172.16.1.182"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/d4bf8bf16e1413866902f476a8bdee90264168facc6bbc66e5e8598d4ce2d9cc
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:b5:69:e2"
        dhcp: false
        addresses:
          - "172.16.1.182/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.16.1.1"
        mtu: 1500
        vip:
          ip: "172.16.1.180"
  - hostname: "talos03"
    ipAddress: "172.16.1.183"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/d4bf8bf16e1413866902f476a8bdee90264168facc6bbc66e5e8598d4ce2d9cc
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:8c:a3:d0"
        dhcp: false
        addresses:
          - "172.16.1.183/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.16.1.1"
        mtu: 1500
        vip:
          ip: "172.16.1.180"
  - hostname: "talos04"
    ipAddress: "172.16.1.184"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/d4bf8bf16e1413866902f476a8bdee90264168facc6bbc66e5e8598d4ce2d9cc
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:05:3d:4e"
        dhcp: false
        addresses:
          - "172.16.1.184/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.16.1.1"
        mtu: 1500
        vip:
          ip: "172.16.1.180"
  - hostname: "talos05"
    ipAddress: "172.16.1.185"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/d4bf8bf16e1413866902f476a8bdee90264168facc6bbc66e5e8598d4ce2d9cc
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:80:51:c1"
        dhcp: false
        addresses:
          - "172.16.1.185/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.16.1.1"
        mtu: 1500
        vip:
          ip: "172.16.1.180"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

