apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password-connect
  namespace: kube-system 
spec:
  destination:
    namespace: kube-system
  # project: default
  source:
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 1.x.x
    chart: connect
    values:
      connect:
        serviceType: ClusterIP
  # syncPolicy:
  #   automated: {}
  #   syncOptions:
  #   - CreateNamespace=true