---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword
  namespace: kube-system
spec:
  interval: 2m
  chart:
    spec:
      chart: connect
      version: 1.17.*
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
        namespace: kube-system
      interval: 5m
  values:
    namespace: kube-system
    connect:
      credentialsName: op-credentials
      credentialsKey: config_data.json
    operator:
      create: false
    serviceType: ClusterIP
