---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password-charts
  namespace: kube-system
spec:
  interval: 10m
  url: https://raw.githubusercontent.com/1Password/connect-helm-charts/
  timeout: 3m
