kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: default
  annotations:
    # io.cilium/lb-ipam-ips: '{{ nginx_external_address }}'
    lbipam.cilium.io/ips: "{{ nginx_external_address }}"
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Cluster