kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: default
  labels:
    pool: "lb-pool"
  annotations:
    lbipam.cilium.io/ips: "172.16.1.192"
    # io.cilium/lb-ipam-ips: '{{ nginx_external_address }}'
    # lbipam.cilium.io/ips: "{{ nginx_external_address }}"
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Cluster