---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: &app nfs-client-provisioner
  namespace: &ns kube-system
spec:
  path: ./kubernetes/kube-system/nfs-client-provisioner/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  prune: true
  interval: 2m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: *app
      namespace: *ns
