---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-client-provisioner
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nfs-client-provisioner
      tag: v4.0.2
    nfs:
      server: "172.16.1.10"
      path: "/appdata"
    storageClass:
      defaultClass: false