---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password-charts
spec:
  interval: 10m
  url: https://raw.githubusercontent.com/1Password/connect-helm-charts/gh-pages/
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: 1.17.x
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
      interval: 5m
  values:
    namespace: external-secrets
    connect:
      credentialsName: op-credentials
      credentialsKey: 1passcredentialsjson
    operator:
      create: true
      credentialsName: op-credentials
      credentialsKey: 1passcredentialsjson
    serviceType: ClusterIP
