---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vault:
        # namespace: "onepassword"
        kubernetes: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
