---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app whoami
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  # healthChecks:
  #   - apiVersion: helm.toolkit.fluxcd.io/v2
  #     kind: HelmRelease
  #     name: *app
  #     namespace: *namespace
  path: ./kubernetes/apps/default/whoami/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  timeout: 5m