---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://helm.cilium.io/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m0s
  wait: true
  timeout: 3m0s
  retryInterval: 2m0s
  path: ./cilium
  prune: true
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
