---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: &app cilium
  namespace: &ns kube-system
spec:
  path: "./kubernetes/kube-system/cilium/app"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  timeout: 2m
  interval: 10m
  retryInterval: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: *app
      namespace: *ns
